name: tests
permissions:
  contents: read
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.5

      - name: go test
        run: go test ./...

      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.24.5
          go-package: ./...

      - name: golint
        run: go run golang.org/x/lint/golint@latest ./...

      - name: govet
        run: go vet ./...
